### PR TITLE
Updated code

### PR DESCRIPTION
**Pull request by vaibhavkhadilkar**
Hi Paolo,

I've added the following things:
1. Pluggable layouts.
2. Vertical partitioning layout.
3. Updated junit tests.
4. Fixed some bugs.

There are a number of commit requests because I was trying to align the structure correctly.

### CODE REVIEW

**Comment by castagna** [comment]
Hi Vaibhav, I've just merged your changes (even if I had problems and a lot of conflicts). However, the testing directory is missing... please, commit it. You can make changed directly to the master branch in the hbase-rdf repo.

**Comment by vaibhavkhadilkar** [comment]
Hi Paolo,

I dont understand which testing folder you mentioned. In the newer version,
all tests have now been moved under src/test. The folder src/main only
contains the sources while src/examples contains a couple of example usages
for the two layouts.

Thanks,
Vaibhav.

**Comment by castagna** [comment]
See: https://github.com/castagna/hbase-rdf/blob/master/src/test/java/com/talis/hbase/rdf/test/HBaseRdfTestSetup.java

... where is the "testing/" directory?

**Comment by vaibhavkhadilkar** [comment]
Got it, It is done.

**Pull request merged**
